# Generated by Django 4.2.3 on 2023-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samostroy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=17, verbose_name='КН')),
                ('status', models.TextField(verbose_name='Статус')),
            ],
        ),
    ]
