# Generated by Django 4.2.3 on 2023-07-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAbLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITN', models.IntegerField(verbose_name='инн')),
                ('name', models.TextField(verbose_name='Название ')),
                ('legalAddres', models.TextField(verbose_name='юр. адрес')),
                ('positionOfHead', models.TextField(verbose_name='Должность руководителя')),
                ('NameOfHead', models.TextField(verbose_name='Имя руководителя')),
                ('ITNofHead', models.IntegerField(verbose_name='Инн руководителя')),
                ('PfoneNumbers', models.TextField(verbose_name='Номер телефона')),
                ('Post', models.EmailField(max_length=254, verbose_name='Почта')),
                ('Site', models.URLField(verbose_name='Сайт')),
                ('DateTocreate', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'информация о юл',
                'verbose_name_plural': 'Таблица с информаций о юл',
            },
        ),
    ]
