"""
Django's settings for myproject project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import psycopg2

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# secret key - секретный ключ, используемый для подписи куки, токенов и других объектов,
# используемых для безопасности приложения.

# try:
#     SECRET_KEY = os.environ["SECRET_KEY"]
# except KeyError as e:
#     raise RuntimeError("Could not find a SECRET_KEY in environment") from e
SECRET_KEY='cbaa45b7774dc2433dcad6c037665c57f2db4fd113a1bf2850e041614093fa0340588b9ced4e7780'

# Debug - определяет, будет ли включен режим отладки.
# Не следует использовать этот режим в продакшн-сервере.
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'rasilka.ru', 'rasilka.online', '82.148.30.81']

# Installed apps - список приложений, которые используются в проекте.
# Регистрируем новые приложения
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dbServer.apps.DbserverConfig',  # можно оставить просто dbServer, но так как написано сейчас потом упростит жизнь
    'CalsPage',
    'EmailPage',
    'EmailCount',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# поменять бд с которыми работаем
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'meadowse',
        'USER': 'meadowse',
        'PASSWORD': 'Comebackplz56!!',
        'HOST': '192.168.0.52',
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS SETTINGS
CORS_ALLOW_ALL_ORIGINS = False  # Разрешить все источники или нет
CORS_ALLOWED_ORIGINS = [
    "https://rasilka.ru",       # Добавьте разрешенные источники
    "https://rasilka.online",  # Другие разрешенные источники
]

CSRF_TRUSTED_ORIGINS = ['https://rasilka.ru', 'https://rasilka.online', ]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = 'media/'

# Add to project/settings.py
SECURE_HSTS_SECONDS = 30  # Unit is seconds; *USE A SMALL VALUE FOR TESTING!*
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Add to project/settings.py
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Allow browsers to load normalize.css from cdn.jsdelivr.net
# CSP_DEFAULT_SRC = ["'self'", "fonts.googleapis.com", "cdn.datatables.net"]
# CSP_STYLE_SRC = ["'self'", "fonts.googleapis.com", "cdn.datatables.net"]
# CSP_STYLE_SRC_ELEM = ["'self'", "fonts.googleapis.com", "cdn.datatables.net"]
# CSP_FONT_SRC = ["'self'", "fonts.googleapis.com", "cdn.datatables.net"]
