# Generated by Django 4.2.3 on 2023-08-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calstable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'информация о звонках',
                'verbose_name_plural': 'Таблица информация о звонках',
            },
        ),
    ]
